
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer



from cgitb import reset
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import QuestionScreen
import homePage
import sounds

def winGame():
    global totalTrueText, totalComboText, totalPointText, highScoreText, lastPoint, lastTrueText, lastComboText
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("./assets/winScreen")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()

    window.geometry("1920x1080")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 1080,
        width = 1920,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        960.0,
        540.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (window.destroy(),homePage.homepage()),
        relief="flat"
    )
    button_1.place(
        x=732.0,
        y=950.0,
        width=61.0,
        height=66.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: (window.destroy(), QuestionScreen.resetQuestions(), QuestionScreen.reset,QuestionScreen.questionScreen()),
        relief="flat"
    )
    button_2.place(
        x=901.0,
        y=906.0,
        width=122.0,
        height=118.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: window.destroy(),
        relief="flat"
    )
    button_3.place(
        x=1127.0,
        y=950.0,
        width=89.0,
        height=65.0
    )

    totalTrueText = canvas.create_text(
        1030.0,
        389.0,
        anchor="nw",
        text=f"{QuestionScreen.trueAnswerPoint}",
        fill="#000000",
        font=("Gugi Regular", 38 * -1)
    )

    totalComboText = canvas.create_text(
        1030.0,
        462.0,
        anchor="nw",
        text=f"{QuestionScreen.comboCounter}",
        fill="#000000",
        font=("Gugi Regular", 38 * -1)
    )

    totalPointText = canvas.create_text(
        1026.0,
        538.0,
        anchor="nw",
        text=f"{QuestionScreen.totalAnswerPoint}",
        fill="#000000",
        font=("Gugi Regular", 38 * -1)
    )

    highScoreText = canvas.create_text(
        1023.0,
        611.0,
        anchor="nw",
        text=f"HighScore",
        fill="#000000",
        font=("Gugi Regular", 38 * -1)
    )

    lastTrueText = canvas.create_text(
        746.0,
        759.0,
        anchor="nw",
        text=f"null",
        fill="#000000",
        font=("Gugi Regular", 32 * -1)
    )

    lastComboText = canvas.create_text(
        940.0,
        759.0,
        anchor="nw",
        text=f"null",
        fill="#000000",
        font=("Gugi Regular", 32 * -1)
    )

    lastPoint = canvas.create_text(
        1110.0,
        760.0,
        anchor="nw",
        text=f"null",
        fill="#000000",
        font=("Gugi Regular", 32 * -1)
    )
    window.attributes("-fullscreen", True)
    sounds.winGameSound()
    window.mainloop()
